name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  

env:
  PROJECT_ID: matching-app-429708
  SERVICE_NAME: tutor-student-matching-app  
  REGION: us-central1 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Using Node.js version 18

    - name: Install dependencies
      run: npm ci  # This uses the package-lock.json for a clean install

    - name: Build React app
      run: npm run build
      env:
        # These secrets should be set in your GitHub repository
        VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
        VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
        VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
        VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
        VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
        VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
        VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --region ${{ env.REGION }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --allow-unauthenticated